import { ResultSetHeader, RowDataPacket } from 'mysql2';
import { CreateTaskInput, Task, TaskStatus } from '../types/task.js';
import { pool } from './../config/database';


// Get All task from the Database
export const findAll = async():Promise<Task[]> => {
    // Task are sorted based on creation time
    const [rows] = await pool.query<RowDataPacket[]>(
        'SELECT id, title, status, created_at FROM tasks ORDER BY created_at DESC'
    );
    return rows as Task[];
}

// Get Task by Id
export const findById = async(id: number):Promise<Task | null> => {
    const [rows] = await pool.query<RowDataPacket[]>(
        'SELECT id, title, status, created_at FROM tasks WHERE id = ?',
        [id]
    );
    return rows[0] as Task;
}

// Create a new task in database
export const createTask = async(taskInput: CreateTaskInput): Promise<Task> => {
    const status: TaskStatus = taskInput.status || 'todo';
    const [result] = await pool.query<ResultSetHeader>(
      'INSERT INTO tasks (title, status) VALUES (?, ?)',
      [taskInput.title, status]
    );
    
    // get id generated by Db
    const newTask = await findById(result.insertId);

    // Make sure the newly created task was successfully retrieved
    if (!newTask) {
      throw new Error('Failed to retrieve newly created task');
    }
    return newTask;
}

// Update only the status of task
export const updateStatus = async(id: number, status: TaskStatus): Promise<Task | null> => {
    const [result] = await pool.query<ResultSetHeader>(
      'UPDATE tasks SET status = ? WHERE id = ?',
      [status, id]
    );

    if (result.affectedRows === 0) return null;

    // Retrieve and return the updated task
    return await findById(id);
}

// Update a task's title, status, or both
// only the field provided by the caller will be updated
export const updateTask = async(id: number, title?: string, status?: TaskStatus): Promise<Task | null> => {
    const updates: string[] = [];
    const values: (string | TaskStatus | number)[] = [];

    // update title if is was there
    if (title !== undefined) {
      updates.push('title = ?');
      values.push(title);
    }

    // update status if it was there
    if (status !== undefined) {
      updates.push('status = ?');
      values.push(status);
    }

    // If no fields were provided, simply return the existing task
    if (updates.length === 0) {
      return await findById(id);
    }

    // Add the task ID to the query parameters
    values.push(id);
    const query = `UPDATE tasks SET ${updates.join(', ')} WHERE id = ?`;
    const [result] = await pool.query<ResultSetHeader>(query, values);

    if (result.affectedRows === 0) return null;

    // Retrieve and return the updated task
    return await findById(id);
}

export const deleteTask = async (id: number): Promise<boolean> => {
  const [result] = await pool.query<ResultSetHeader>(
    'DELETE FROM tasks WHERE id = ?',
    [id]
  );

  // affectedRows tells us whether a task was actually deleted
  return result.affectedRows > 0;
};
